### ISSUE TITLE
Hello, is it possible to get an example of the bptd module in action?

### ISSUE THREAD

**Issue by Geldren1** [aschein/bptd#2]
Hello there, first of all many thanks for providing this code. I heard Hanna talk about your work and I am very excited about bptd and wish to use it myself in my research.  I am just getting to grips with this, including learning python and I would like to ask for a basic example of calling this module and the input and output. Not to worry if not, as you say you do not support it and providing the code has already given me more than a leg-up!

**Comment by aschein** [comment]
Hi @Geldren1, I've added a toy example of fitting the model to a count tensor in the readme.  I will also be pushing a new implementation of the model soon, which is more efficient and uses variable names more consistent with the paper.  If you have any questions, let me know.

**Comment by Geldren1** [comment]
Many many thanks, and additional thanks for posting so quickly!
